services:
  app:
    build: .
    ports:
      - "8084:8080"
    depends_on:
      - redis
    environment:
      - TZ=America/Los_Angeles
      - PORT=8080
      - REDIS_HOST=redis
    env_file:
      - .env
    restart: always

  redis:
    image: redis:latest
    environment:
      - TZ=America/Los_Angeles
    restart: always
